### PR TITLE
Fix Logo Icons and Reorder Team Members

### PR DESCRIPTION
**Pull request by njlyon0**
Two changes:
- Changed hack-y GitHub/Twitter logos to use fontawesome
    - Was HTML inserts of 2% width PNGs of each logo
    - Now uses `{{< fa brands github >}}` and the equivalent for Twitter
- Alphabetized our team members order

### CODE REVIEW

**Comment by angelchen7** [comment]
The icons look great! One thing: you're putting yourself *after* Althea in the alphabetical order? 🤔

**Comment by njlyon0** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Ftenor.com%2Fview%2Five-made-a-huge-mistake-mistake-oops-regret-disappointed-gif-4332242&psig=AOvVaw2j_CJgOPfFgadvF-iqkkag&ust=1667759581661000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCOi98NzWl_sCFQAAAAAdAAAAABAE

**Comment by njlyon0** [comment]
Fixed!

**Review by angelchen7 — APPROVED** [review]
Looks good to me! I sang the abc song just to make sure the order is correct :)

**Pull request merged**
