### PR TITLE
Suggestion for "Our Team" Formatting

### PR DESCRIPTION
**Pull request by njlyon0**
Put in my blurb and a GitHub/Twitter logo to put next to links to those sites and allow us to crosslink our profiles elsewhere.

Also added the .Rproj file to the .gitignore just to avoid people accidentally committing it in the future / clean up the Git pane (for those of us using RStudio)

### CODE REVIEW

**Review by dvirlar2 — COMMENTED** [review]
I'm mostly working in VS Code, so the commit to move the `.Rproj` file doesn't really affect me 😅  That being said, I think this is totally fine given the previous conversations we've had about this

**Review by dvirlar2 — APPROVED** [review]
Specifically approving the `.Rproj` file addition to the `.gitignore` file

**Review by dvirlar2 — APPROVED** [review]
I think it's better to at least have something down in the about us section that we can all merge to our own branches and tinker with. 

Personally, I think I want to try something closer to what @samanthacsik did [here](https://samanthacsik.github.io/talks/2021-12-15-data-science-with-r-python/) underneath the blog title ([code](https://github.com/samanthacsik/samanthacsik.github.io/blob/main/_talks/2021-12-15-data-science-with-r-python/data-science-with-r-python.Rmd)). _**But**_ I'd rather tinker with that using the general structure you've already built out. Soooo I'm approving the PR 👀

**Comment by njlyon0** [comment]
Thanks Daphne! And yeah, my hope was to make the file we can tinker with more than proposing a set-in-stone format for our bios

**Pull request merged**
